version: '3.8'

services:
  db:
    image: postgres:13
    container_name: hal9001_db
    environment:
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: hal9001
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hal9001_net

  app:
    build: .
    container_name: hal9001_app
    environment:
      - DB_USERNAME=your_db_username
      - DB_PASSWORD=your_db_password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=hal9001
    depends_on:
      - db
    networks:
      - hal9001_net
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  hal9001_net:

